import { Router } from "express";
import rateLimit from "express-rate-limit";
import * as aiController from "../controllers/ai.controller.js";
import { authMiddleware, requireVerifiedEmail } from "../middleware/auth.middleware.js";
import { requireUsage } from "../middleware/usage.middleware.js";
const router = Router();
const limiter = rateLimit({ windowMs: 60 * 1000, max: 20, message: { success: false, message: "Too many requests" } });
router.use(authMiddleware, requireVerifiedEmail, limiter);
router.post("/chat", requireUsage("aiMessages"), aiController.chat);
router.post("/plan", requireUsage("brainDumps"), aiController.plan);
export default router;
